version: '3.8'

services:
  duke-energy-server:
    build: .
    container_name: duke-energy-server
    ports:
      - "3001:3000" 
    volumes:
      # Mount the data directory from the parent project
      - ../data:/app/data
    environment:
      - NODE_ENV=production
      - DATA_DIRECTORY=/app/data
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: duke-energy-network